# Generated by Django 4.2.7 on 2024-07-09 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSmtpCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('_password', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
