# Generated by Django 4.2.7 on 2024-07-10 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usersmtpcreds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmtpcreds',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_creds', to=settings.AUTH_USER_MODEL),
        ),
    ]
