# Generated by Django 4.2.7 on 2024-07-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usersmtpcreds_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmtpcreds',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usersmtpcreds',
            name='smtp_server',
        ),
        migrations.AddField(
            model_name='usersmtpcreds',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersmtpcreds',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
