services:

  redis:
    image: redis
    ports:
      - 6379:6379

  django:
    container_name: django
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - SMTP_MAIL=${SMTP_MAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - postgres_db
      - redis

  celery:
    container_name: celery
    build:
      context: ./
    command: 
      - celery
      - -A
      - mailer
      - worker
      - --loglevel=info
    volumes: 
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - SMTP_MAIL=${SMTP_MAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - postgres_db
      - redis


  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 6543:5432
  

volumes:
  postgres_data:
