# Generated by Django 5.0.6 on 2024-06-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='bounce_count',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='outgoingmails',
            name='template',
        ),
        migrations.AddField(
            model_name='outgoingmails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
