# Generated by Django 5.0.6 on 2024-06-30 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_email_bounce_count_remove_email_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailmaillist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailmaillist',
            name='mail_list',
        ),
        migrations.RemoveField(
            model_name='maillist',
            name='email',
        ),
        migrations.DeleteModel(
            name='TemplateModel',
        ),
        migrations.AddField(
            model_name='email',
            name='bounce_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='email',
            name='mail_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.maillist'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mail_lists',
            field=models.ManyToManyField(related_name='campaigns', to='core.maillist'),
        ),
        migrations.DeleteModel(
            name='EmailMailList',
        ),
    ]
