# Generated by Django 5.0.6 on 2024-07-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_email_mail_list_alter_email_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='mail_lists',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='core.maillist'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], db_index=True, default='draft', max_length=10),
        ),
    ]
