# Generated by Django 5.0.6 on 2024-07-02 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_campaign_mail_lists_alter_campaign_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingmails',
            name='delivery_attempts',
        ),
        migrations.RemoveField(
            model_name='outgoingmails',
            name='is_active',
        ),
        migrations.AddField(
            model_name='outgoingmails',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign'),
        ),
    ]
