# Generated by Django 5.0.6 on 2024-07-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_outgoingmails_delivery_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='mail_lists',
            new_name='maillists',
        ),
    ]
