# Generated by Django 5.0.6 on 2024-07-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campaign_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmaillist',
            old_name='mail_list',
            new_name='maillist',
        ),
        migrations.AlterUniqueTogether(
            name='emailmaillist',
            unique_together={('email', 'maillist')},
        ),
    ]
