# Generated by Django 4.1.4 on 2024-07-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_mail_list_emailmaillist_maillist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
