# Generated by Django 4.2.7 on 2024-07-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_outgoingmails_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject',
        ),
    ]
