# Generated by Django 4.2.7 on 2024-07-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_maillist_name_alter_email_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
